frappe/agent

agent/pages/suspended_saas.html, agent/proxy.py, agent/templates/proxy/nginx.conf.jinja2
Shows a different suspension via proxy for SaaS sites to redirect users to SaaS dashboard instead of Frappecloud dashboard
=> feat: Show different suspension page for SaaS sites

agent/server.py, agent/site.py
* Some regions need the region_name to be explicitly while uploading an object
=> fix: Cluster backups for unsupported regions

agent/server.py, agent/site.py
Rebuild search index happens in background which may not end before recover site migrate job. This ends up leaving residue in site directory preventing further updates. 
Moving it to foreground as separate step after migrate should fix this.
=> fix(Site): Move build search index to separate step

.pre-commit-config.yaml, agent/proxy.py, agent/tests/test_proxy.py, agent/web.py, requirements.txt
As tested on 4 core (for more nginx processes) machine and running 1000+ jobs
=> fix: Don't over-reload nginx for suspends and archives

.pre-commit-config.yaml, agent/bench.py, agent/tests/test_site.py
- ci: Add args to flake8 like in press for precommit
- fix(Bench): Add hack to show output in agent job
- fix(Bench): Censor sensitive keys in output
- fix(Bench): Include directory information when throwing err
=> feat: Show invalid site config when present

agent/templates/bench/supervisor.conf
Problem:
- Prerequisite: long running reqeust is going on.
- `bench restart` is requested.
- supervisord sends sigterm to gunicorn master process.
- gunicorn passes it to all child workers and waits for graceful shutdown (30 seconds)
- supervisord has no chill, and sends sigkill to master process in 10 seconds
- gunicorn master proesss is dead, so now child workers will keep running until they complete request which can take a really long time.
- This entire time the sites will be down.
Fix:
- Explicitly encode default graceful_timeout in config - 30 seconds.
- Make supervisor wait 10 more seconds for gunicorn to do its thing, then only send sigkill.
=>  fix: Prevent Gunicorn child workers hangup

agent/bench.py, agent/templates/bench/supervisor.conf
For more details check: https://github.com/frappe/press/pull/1255
Other worker types are anyways not supported, so either sync workers (0 threads) or gthread workers (>0 threads)
=> refactor: set worker class to gthread if threads > 0

requirements.txt
This version is unusable and crashes while attempting to autocomplete.
=> build: update ipython dependency

agent/templates/bench/nginx.conf.jinja2
- Proxy nginx forces remote_addr which is true IP
- App server nginx still forces remote_addr which is actually proxy
server IP.
So proxy server shouldn't force remote_addr but instead only set it if unset.
https://github.com/frappe/agent/blob/81e30c6876e647fc5ca869d571053dd07251c202/agent/templates/proxy/nginx.conf.jinja2#L169
As per my understanding:
=> fix: Set correct remote_addr

agent/database.py
Binary log browser is unintuitive to use with filters, the "max lines"
is applied before filtering.
Since we have bounded size of bin log (100MB per file) just reading
everything which is ~= 100MB of text is fine IMO.
=> fix: Apply limit on matching rows, not read rows

agent/site.py
Instead of handling single quotes in text manually, use shlex.
=> fix: use shlex.quote to handle quotation in name before passing to subprocess

agent/__init__.py, agent/analytics.py, agent/app.py, agent/base.py, agent/bench.py, agent/builder.py, agent/cli.py, agent/database.py, agent/docker_cache_utils.py, agent/exceptions.py, agent/job.py, agent/minio.py, agent/monitor.py, agent/patch_handler.py, agent/patches/__init__.py, agent/patches/add_agent_id_field.py, agent/proxy.py, agent/proxysql.py, agent/security.py, agent/server.py, agent/site.py, agent/ssh.py, agent/tests/__init__.py, agent/tests/test_proxy.py, agent/tests/test_site.py, agent/usage.py, agent/utils.py, agent/web.py
Fool me twice...
Fix issues caused by dumb shit like this: https://github.com/frappe/agent/commit/a9a020565cd24b0e24bf4203c1bc48100ce12c9e
Adding the line converts annotations into strings before runtime:
=> fix: `from __future__ import annotations`

.github/workflows/main.yml, .pre-commit-config.yaml, agent/__init__.py, agent/app.py, agent/base.py, agent/bench.py, agent/builder.py, agent/cli.py, agent/database.py, agent/docker_cache_utils.py, agent/job.py, agent/minio.py, agent/monitor.py, agent/patch_handler.py, agent/patches/add_agent_id_field.py, agent/proxy.py, agent/proxysql.py, agent/security.py, agent/server.py, agent/site.py, agent/ssh.py, agent/tests/test_proxy.py, agent/tests/test_site.py, agent/usage.py, agent/utils.py, agent/web.py, ruff.toml
- Use Ruff for linting and formatting
- Add lint and format check to CI
- Enable: `["F", "E", "W", "I", "UP", "B", "RUF", "FA", "TCH", "C90", "RET", "SIM"]` ([ref](https://docs.astral.sh/ruff/rules/))
- Refactor code to appease the enabled rules
=> fix: use ruff for linting, formatting

agent/bench.py
All `.json` changes will trigger a migrate.
Skip diff check if the hashes match.
=> fix: minor fixes to inplace updates

agent/database.py, agent/site.py, agent/tests/test_database.py, agent/web.py
Fixes https://github.com/frappe/press/issues/2237
---
=> feat: db users and permission manager

agent/site.py, agent/utils.py
Fixes https://github.com/frappe/press/issues/2262
It will log filename and SHA256 checksum of
- Database File
- Private File [If exists]
- Public File [If exists]
If `Site Resore` fails, sha256 checksum will be calculated and logged in agent job. 
If `Site Restore` is successful, it will not calculate checksum of file
=> feat: show hash of downloaded backup files on restore failure

agent/database.py
- Based on various db versions, the perf schema views might be available or not
- It's better to use the SQL queries  instead to avoid any uncertainty
References of views -
- https://mariadb.com/docs/server/ref/mdb/sys/statements_with_full_table_scans/
- https://mariadb.com/docs/server/ref/mdb/sys/schema_redundant_indexes/
- https://mariadb.com/docs/server/ref/mdb/sys/schema_unused_indexes/
=> chore(db-perf-schema): avoid using database performance schema views

agent/job.py, agent/web.py
Jobs that timeout, or are forcefully killed never log the status to JobModel.
If rq status is terminal and JobModel.status is non-terminal. Then treat rq status as the ground-truth
Closes https://github.com/frappe/agent/issues/101
=> fix(rq): Use rq job status for timed-out and killed jobs

agent/templates/bench/nginx.conf.jinja2
1. Make `/assets` cache immutable, they have hashes anyway.
2. Add cache headers to typically cacheable files like images and media `/files/*` (copied the list from press)
3. Private files via framework: https://github.com/frappe/frappe/pull/29221 
In the worst case, `ctrl+shift+r` fixes any kind of stale cache anyway because they send `no-cache` header to the server. `/files/*` also have etag so even after invalidation it will just be refreshed using the etag.
The numbers are still not _that_ aggressive but they are better than 0, we can increase over time if we don't see any issue.
=> perf: Add aggresive cache-control headers for files and assets

agent/proxy.py
This is to avoid failures like this on add/rename site jobs
```shell
systemd[1]: Reloading A high performance web server and a reverse proxy server.
nginx[541919]: nginx: [emerg] conflicting parameter "frappemail.frappe.cloud" in /etc/nginx/conf.d/proxy.conf:3722
systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: Reload failed for A high performance web server and a reverse proxy server.
```
Reference: https://frappecloud.com/app/agent-job/3d4bd1ab06
=> fix(proxy): Remove conflicting site before adding a new site

agent/templates/bench/supervisor.conf
- Enable SO_REUSEPORT optimization for better load balancing
- It also avoids waking up every worker for 1 request
- Lower max connections to # of threads. Why accept more than what is servicable
here? Default is 1000! Changed it to 2x thread count. 2x is to accommodate keepalive connections and reduce TTFB during heavy workloads. Keeping it the same as the thread count will result in a serial chain from kernel to `gthread` threadpool manager to worker.
- Mirror `keepalive` timeout with nginx, both are now 15 seconds.
=> perf: optimize for gthread

agent/templates/bench/supervisor.conf
This can cause a random smallish downtime when there's only 1 worker on bench.
=> fix: Avoid auto restarting in single worker setups

agent/templates/bench/supervisor.conf
- gthread by default accepts up to 1000 connections
- it can only serve `nthreads` requests at any time i.e. 2-6 in our deployments.
- So when worker dies it might have accepted 10s of requests which all get cancelled resulting in `502` error. 
Fix:
- Don't keep connections alive
- Limit accepted connections to `n+1` where `n` is number of threads. `n+1` avoids serial chain of `accept` -> `threadpool` and ensures better threadpool utilization. 
Note: diff says +2 because there's an off by one error in gunicorn logic, that doesn't matter much, we just need to avoid accepting huge number of requests +1 or +2 are both fine)
Things I verified:
- Throughput is not affected / only marginally affected for silly things like `ping` i.e. threadpool utilization is just fine.
- max futures never …
=> fix: limit connections a worker can accept at any time

agent/bench.py, agent/exporter.py, agent/templates/agent/nginx.conf.jinja2, agent/web.py, requirements.txt
Closes frappe/press#1283
- Adds endpoint to fetch RQ metrics for all benches on server
- Adds endpoint to fetch RQ metrics per bench
- Exempts all benches endpoint from token validation	
- Will be proxying this through nginx metrics endpoints and that has it's own validation setup
- Force redirect the agent endpoint to nginx one
~~TODO~~:
- Add to `nginx.conf`
```
location /agent/benches/metrics {
return 301 /metrics/rq;
}
```
```
location /metrics/rq {
proxy_pass http://127.0.0.1:25052/benches/metrics;
}
```
=> feat(exporter): Add endpoint for RQ metrics

agent/database_physical_backup.py, agent/database_physical_restore.py
`Sequence` tables are also InnoDB.MyISAM tables.
But in `mariadb-dump` output, the create/drop command for sequence table is different.
So, we should handle those specially.
https://mariadb.com/kb/en/create-sequence/
https://mariadb.com/kb/en/drop-sequence/
=> feat(physical-restore): Handle Sequence Table specially

agent/database_physical_restore.py
After restoration, check all the restored tables
In case of MyISAM, table can corrupt due to mismatch in count So, do REPAIR TABLE ... USE_FRM to repair
In InnoDB table, fulltext index will not import via physical restore We need to rebuild that index
=> fix(physical-restore): Validate and fix tables after restoration

agent/database_physical_restore.py
- refactor(physical-restore): Repair innodb tables with fulltext index
- refactor(physical-restore): Avoid checking all innodb tables
- refactor(physical-restore): For myisam table, on warning do repair
=> refactor(physical-restore): Optimize table validations and repair

agent/database_physical_restore.py
_Whatever MariaDB docs tell, doesn't work as it is for physical restore_
**InnoDB FullText Index Repair -**
- Drop the FTS indexes from table first
- `OPTIMIZE TABLE` for that specific table to fix corruptions. 
If we don't do it, there will be almost no noticable issues. But, on fulltext index creation database will crash.
```
2025-03-10 09:37:32 0x7ff50c221700  InnoDB: Assertion failure in file /home/buildbot/buildbot/build/mariadb-10.6.21/storage/innobase/pars/pars0pars.cc line 771
InnoDB: Failing assertion: sym_node->table != NULL
250310  9:37:32 [ERROR] /usr/sbin/mariadbd got signal 6 ;
Query (0x7ff3c4010c30): ALTER TABLE `tabHD Ticket` ADD FULLTEXT INDEX `hd_ticket_content`
```
- Create the FTS indexes again.
=> fix(physical-restore): InnoDB FTS Index Repair

agent/database_physical_backup.py, agent/database_physical_restore.py
Fixes https://github.com/frappe/press/issues/2564
We will deactivate site before site backup/restore
Ideally there shouldn't be any active connection on the database.
External connection through proxysql or from press itself (might be devtools), can block execution of backup/restore process.
So, before every important steps kill the active database connections of the database.
=> feat: Kill active database connection before backup/restore

agent/bench.py, agent/utils.py, agent/web.py, requirements.txt
Addresses [this](https://github.com/frappe/press/issues/2450)
REQUIRES
- frappe ALL = (root) NOPASSWD: /home/frappe/agent/env/bin/py-spy
in /etc/sudoers.d/frappe on all agent servers.
=> feat: Snapshots to facilitate stuck process investigation

agent/server.py
* Old agents don't have press url in their config.
=> fix: backwards support for missing press url

agent/site.py
Fixes https://github.com/frappe/agent/issues/187
- Increase timeout to 5 minutes from 2 minutes.
- If still the jobs in site doesn't finish/stop within that time , just abort the operation
=> fix: Ensure `Wait for Enqueued Jobs` step does not fail silently

agent/app.py, agent/base.py, agent/bench.py, agent/cli.py, agent/proxy.py, agent/server.py, agent/site.py
Fixes https://github.com/frappe/press/issues/2617
Ensure two things -
- Atomic writes, so that if someway 2 writers start writing the file, the file doesn't corrupt. At max, we will lose one copy of file. [Need to write content to some tmp file and then do `os.rename`]
- Don't allow multiple writes or dirty reads, in `update_config` or `set_config` functions.
=> fix: Ensure atomic writes while writing config files

agent/cli.py
Fixes https://github.com/frappe/agent/issues/196 (1 of 2 issues)
https://github.com/frappe/agent/blob/d637bdf564cd5c9b51bccbcacc73ca6577528e9b/agent/web.py#L1363-L1378
This endpoint is used to poll bulk jobs from server by press.
It doesn't use any indexed column to search, instead use `agent_job_id` , which is actually the `name/id` of `Agent Job` on press. 
---
Indexing can make it way too fast here.
The sqlite database is 29GB
**Before Indexing -**
😅 7.5s
**After Indexing -**
<1ms
=> perf(poll): Add index to agent_job_id field

agent/proxy.py
Traceback (most recent call last):
File "/home/frappe/agent/env/bin/agent", line 11, in <module>
load_entry_point('agent', 'console_scripts', 'agent')()
File "/home/frappe/agent/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/home/frappe/agent/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/home/frappe/agent/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/agent/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/frappe/agent/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
return …
=> Fix AttributeError: '_config_file_lock' in Proxy Class Initialization

agent/cli.py, agent/server.py, agent/templates/agent/supervisor.conf.jinja2, agent/utils.py
Related https://github.com/frappe/press/issues/2660
**Tasks -**
- Web worker
- BG Worker
- Redis
---
**agent update**
```python
@click.option("--restart-web-workers", default=True)
@click.option("--restart-rq-workers", default=True)
@click.option("--restart-redis", default=True)
@click.option("--skip-repo-setup", default=False)
```
=> revamp: Better update and rollback support

agent/builder.py, agent/exceptions.py, agent/server.py
Checks registry health before and after a push, if container is being restarted or is down retry after 60 seconds, for a max of 3 retries.
=> feat(registry): Check registry status before image push

agent/templates/nginx/nginx.conf.jinja2
After moving to arm, looks like the default has been reduced tto 4k And that's causing issues randomly on some servers
=> fix(nginx): Set proxy buffer to 8kb

agent/templates/agent/nginx.conf.jinja2, agent/templates/proxy/nginx.conf.jinja2
We have set a busy buffer size to 8k in server block so, now it's imporant to add busy_buffer_size
wherever we have configure buffer_size
=> fix(nginx): Set busy buffer size in agent config
