agent/server.py, agent/web.py
* Added new agent job `reload_nginx`
=> feat: reload nginx job

agent/templates/proxy/nginx.conf.jinja2
increased it from 50m to 250M
Fixes https://github.com/frappe/press/issues/591
=> fix: increase upload limit in proxy (50m -> 250M)

agent/server.py
fixes https://github.com/frappe/press/issues/626
PS: The archive job will still fail if the bench is broken due to New Bench failed job.
=> fix: check if bench exists

agent/server.py, agent/site.py, agent/web.py
- Get scripts as a string from press
- Run each script in console (of site)
!not tested
=> fix(ux): run before migrations scripts

agent/database.py, agent/web.py
endpoints for https://github.com/frappe/press/pull/811
=> feat: deadlock browser

agent/site.py
Returns a response with config_file included in the backup
Needed for frappe/press#861
=>  feat(site-backup): Download site config file

agent/bench.py, agent/cli.py, agent/exceptions.py, agent/job.py, agent/patch_handler.py, agent/patches.txt, agent/patches/add_agent_id_field.py, agent/patches/setup_patch_log.py, agent/server.py, agent/web.py
- Add the FC agent job to the job table
- Provision to write patch
- API to poll based on FC's agent job id
=> feat: provision to retry jobs via fc

agent/bench.py, agent/templates/bench/supervisor.conf
press: https://github.com/frappe/press/pull/1218
=> feat: Configurable gunicorn worker types

agent/site.py, agent/web.py
required for https://github.com/frappe/press/issues/1265
Refer https://github.com/frappe/frappe/pull/23813 and https://github.com/frappe/frappe/pull/23787 for Framework commands.
=> feat: fetch table stats

agent/database.py, agent/web.py
significantly speeds up https://github.com/frappe/press/issues/1265
Relevant press PR WIP.
=> feat: fetch column stats

agent/bench.py, agent/templates/bench/supervisor.conf
https://github.com/frappe/press/pull/1262
=> fix: supervisor run code server only if enabled

agent/cli.py, agent/exceptions.py, agent/job.py, agent/patch_handler.py, agent/patches/add_agent_id_field.py, agent/site.py
- fix(Site): Always install app with force
- refactor(Site): Add some typing
- style: black
https://github.com/frappe/press/issues/1231
=> fix(Site): Always install app with force

agent/bench.py, agent/templates/bench/supervisor.conf
press: https://github.com/frappe/press/pull/1376
=> feat: RQ workerpool

.gitignore, agent/base.py, agent/builder.py, agent/job.py, agent/web.py, requirements.txt
Related https://github.com/frappe/press/issues/1328
=> feat: remote docker image build support

agent/bench.py, dev-requirements.txt, requirements.txt
- chore: Add filelock to requirements
- chore: Add dev-requirements
- chore: Add regular black to dev requirements
- fix(Bench): Create lock before updating bench nginx config
fixes https://github.com/frappe/press/issues/1369
=> feat(Bench): Don't update nginx config in parallel

agent/base.py, agent/bench.py, agent/web.py
https://github.com/frappe/press/pull/1587
=> feat: press dashboard supervisorctl access

agent/base.py, agent/bench.py, agent/web.py
Reverts frappe/agent#88
This broke everything, need to figure out why
=> Revert "feat: press dashboard supervisorctl access"

agent/base.py, agent/bench.py, agent/web.py
Reverts frappe/agent#89
I figure out what went wrong
=> Revert "Revert "feat: press dashboard supervisorctl access""

agent/base.py, agent/bench.py, agent/builder.py, agent/job.py, agent/web.py
Description: https://github.com/frappe/press/pull/1631
Refactors: https://github.com/frappe/agent/pull/83
=> refactor: remote builder

agent/builder.py, agent/docker_cache_utils.py, agent/web.py
https://github.com/frappe/press/pull/1699
=> fix: don't throw on build fail

agent/bench.py, agent/web.py
to create system user on site during trial site creation
=> feat: add create-user endpoint

agent/site.py, agent/web.py
support code for https://github.com/frappe/press/pull/1942
=> feat :Add database index

agent/bench.py, agent/web.py
Related https://github.com/frappe/press/pull/1986
=> feat: allow to provide payload for system user creation while new site job

agent/bench.py, agent/site.py, agent/web.py
Related https://github.com/frappe/press/pull/2018
=> feat: added job for complete setup wizard of site

README.md, agent/cli.py, requirements.txt
`agent console` will spawn iPython console with instantiated `Server` object if `config.json` is found.
=> feat: ipython agent console

agent/bench.py, agent/web.py
Press PR - https://github.com/frappe/press/pull/2113
=> feat: support to update config in rename site job

.github/workflows/main.yml, agent/tests/test_site.py
Spent a stupid amount of time trying to get the tests to work. One of them has been skipped due to a kind of inexplicable error which I don't have the patience to debug right now.
The tests are meant as a sanity check to ensure that the agent code is valid python 3.8
=> chore: run unittests on GA

agent/proxysql.py, agent/web.py
Related https://github.com/frappe/press/issues/2315
=> feat(proxysql): add support to configure max database connection

agent/builder.py, agent/web.py
Uses [docker multi-platform builds](https://docs.docker.com/build/building/multi-platform/).
Defaults to linux/amd64 (x86_64)
=> feat(arm): Support multi-platform builds

agent/database.py, agent/database_optimizer.py, agent/database_server.py, agent/site.py, agent/tests/test_database_optimizer.py, agent/web.py, requirements.txt
Related https://github.com/frappe/press/issues/2296
Related https://github.com/frappe/press/issues/2358
- /benches/<string:bench>/sites/<string:site>/database/processes
- /benches/<string:bench>/sites/<string:site>/database/kill-process/<<string:pid>>
=> feat(database): db performance insights

agent/web.py
=> fix(web): Throw readable tracebacks for AgentException

agent/database_physical_backup.py, agent/database_physical_restore.py, agent/server.py, agent/site.py, agent/utils.py, agent/web.py
Resolve https://github.com/frappe/press/issues/1093
=> feat(database): Physical Backup & Restore

agent/database_physical_backup.py, agent/database_physical_restore.py, agent/web.py
Press PR https://github.com/frappe/press/pull/2463
=> refactor(physical-backup): Store metadata in disk snapshot

agent/cli.py
Added command to run py-spy with sudo privileges
Ref: https://github.com/frappe/agent/pull/178
=> feat(py-spy): Added agent command to enable pyspy

agent/cli.py
=> refactor(naming): Better naming

agent/cli.py, agent/nginx_defer_reload.py, agent/proxy.py
Every 2 minutes it will check if reload required.
So in `skip_reload`, instead of skipping reload completely forever, we can group and execute a reload later.
=> feat(nginx): Defer Reload

agent/patches.txt, agent/patches/add_index_on_agent_job_id_field.py, agent/patches/add_index_on_jobmodel_id_field.py
- Added index on id field of job model
- Move the code for adding index from cli to separate patch
=> perf: Index the id field of jobs

agent/server.py, agent/web.py
- Pull docker images using tags sent by press.
=> feat(images): Add job to pull images on vm

agent/application_storage_analyzer.py, agent/server.py
- Analyse docker overlay2 storage
- We don't show individual layer breakdown obviously just calculating root entry point storage
=> feat(storage): Docker disk usage

agent/application_storage_analyzer.py, agent/server.py
Provide calculation for additional storage usage (overlay2; assets; env; node_modules etc.).
=> chore(storage): Add additional disk usage calculation

agent/builder.py, agent/server.py, agent/utils.py
In case of registry being unavailable due to restarts; wait for backoff and retry establishing connection.
=> feat(registry): Registry retry

agent/application_storage_analyzer.py, agent/server.py, agent/utils.py, agent/web.py
- Allow force cleanup
- Ignore added layer of timestamp verification in case of force cleanup
=> feat(cleanup): Allow force cleanup of unused files

.github/workflows/main.yml, .pre-commit-config.yaml, agent/cli.py, agent/server.py, agent/templates/agent/supervisor.conf.jinja2
- **ci(pre-commit): Remove deprecated stuff**
- **fix(server): Add nginx reload manager to standalone setup**
=> fix(server): Add nginx reload manager for standalone setup
